repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3.9
        exclude: ^nbs/
  - repo: https://github.com/pycqa/flake8
    rev: '6.0.0'  # pick a git hash / tag to point to
    hooks:
      - id: flake8
        exclude: ^nbs/
  - repo: https://github.com/fastai/nbdev
    rev: 2.2.10
    hooks:
    - id: nbdev_clean
