[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "mlde_analysis"
authors = [
  { name="Henry Addison", email="henry.addison@bristol.ac.uk" },
]
description = "A package for notebooks evaluating approaches to emulate a CPM and downscale precipitation"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "cf-xarray~=0.10.5",
  "cmcrameri~=1.9",
  "cmweather~=0.3.2",
  "ipympl~=0.9.7",
  "mlde-utils==v0.3.5",
  "nbdev~=2.4",
  #"netcdf4==1.7.2",
  "properscoring~=0.1",
  "python-cmethods~=2.3",
  "xhistogram~=0.3.2",
  "xskillscore~=0.0.26",
  "statsmodels~=0.14.4",
]
dynamic = ["version"]

[dependency-groups]
test = ["pytest", "pytest-env"]
dev = [{include-group = "test"}]

[project.urls]
"Homepage" = "https://github.com/henryaddison/mlde-analysis"
"Bug Tracker" = "https://github.com/henryaddison/mlde-analysis/issues"

[project.scripts]
    mlde-analysis = "mlde_analysis.bin:app"

[tool.pixi.workspace]
channels = ["conda-forge", "nodefaults"]
platforms = ["linux-64"]

[tool.pixi.environments]
default = {features = [], solve-group = "default"}
dev = {features = ["dev"], solve-group = "default"}
# Create a custom environment which only has the `lint` feature
# lint = {features = ["lint"], no-default-feature = true}


[tool.pixi.dependencies]
black = { version = "~=25.1.0" }
bottleneck = { version = "~=1.5" }
dask = { version = "==2025.11.0" }
flake8 = { version = "~=7.3" }
iris = { version = "~=3.12" }
jupyterlab = { version = "~=4.4" }
metpy = { version = "~=1.7.0" }
nc-time-axis = { version = "==1.4.1" }
numpy = { version = "~=2.3" }
papermill = { version = "~=2.6" }
pint = { version = "~=0.24.4" }
pysteps = { version = "~=1.17" }
python = { version = "~=3.12.11" }
python-cdo = { version = "~=1.6" }
python-dotenv = { version = "~=1.2.0" }
scikit-learn = { version = "~=1.7" }
scipy = { version = "~=1.15" }
seaborn = { version = "~=0.13.2" }
typer = { version = "~=0.16.0" }
xarray = { version = "==2025.12.0" }
h5netcdf = ">=1.7.3,<2"
hdf5plugin = ">=6.0.0,<7"
zarr = ">=3.1.5,<4"
dask-gateway = ">=2026.3.0,<2027"
flox = ">=0.11.2,<0.12"
hvplot = ">=0.12.2,<0.13"
geoviews = ">=1.15.1,<2"

[tool.pixi.pypi-dependencies]
mlde_analysis = { path = ".", editable = true }

[tool.pixi.feature.dev.dependencies]
pre-commit = "~=4.5"
flake8 = { version = "~=7.3" }
black = { version = "~=25.1.0" }
dask-labextension = ">=7.0.0,<8"

[tool.pixi.feature.dev.tasks]
test = "pytest"
lint = "black .; flake8 ."

[tool.black]
extend-exclude = '^/nbs/'
target-version = ["py312"]

[tool.pytest_env]
DATA_PATH="/path/to/data"
DERIVED_DATA= {value = "{DATA_PATH}/derived", transform = true}
WORKDIRS_PATH="/path/to/test/workdirs"
